= Installing Chrome-OS Flex on Macbook Air 2010
:docdate:
:experimental: 
:xrefstyle: short
:toc: 
:sectnums:
:idprefix:
:idseparator: -

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Purpose
This document contains a report of experiences gathered after installing Chrome OS Flex on a MacBook Air 11 inch, model of late 2010. There are several reports available on the internet but most are related to newer hardware and hardware with better specifications. The installation of Chrome OS on this laptop resulted only in a part success. At first everything seemed to work fine and the performance was extraordinary. But what started with small glitches on the display sometimes resulted in long periods during which the screen was frozen and sometimes even a complete crash. The glitches in the display looked very similar to the glitches experienced earlier with an installation of Linux on the same laptop. This is a known issue reported earlier (see https://support.google.com/chromeosflex/answer/11541806#zippy=%2Cnvidia-graphics-are-generally-unstable). 

== Specification of the MacBook
The late 2010 model of MacBook used for this experiment had the following specifications: 

**Processor and memory**

* 1.4GHz Intel Core 2 Duo processor with 3MB on-chip shared L2 cache; 
* 800MHz frontside bus
* 4GB of 1066MHz DDR3 SDRAM onboard (4GB maximum)

**Storage** 

* Flash Storage 64GB, upgraded later to 256 Gbyte

**Graphics**

* NVIDIA GeForce 320M graphics processor with 256MB of DDR3 SDRAM shared with main memory3



== Graphics issues 



_________________________________________ 
NVIDIA graphics are generally unstable

*Known issue* 

Devices using Nvidia GPUs are likely to be unstable and exhibit display flickering when under heavy GPU load. 

Devices using the Quadro NVS 4200M are not recommended for use. 
Multiple generations of Intel GPUs are unsupported on ChromeOS Flex and will not boot it.

Intel Generation 3 and older, including GMA 900, 950, 3100, 3150
Intel PowerVR graphics, including GMA 500, 600, 3600, 3650
________________________________________

https://blog.virtualwolf.org/installing-linux-mint-19-1-on-a-late-2010-macbook-air/
https://wiki.archlinux.org/title/MacBookPro7,1#Nvidia%5B/url%5D
https://askubuntu.com/questions/264247/proprietary-nvidia-drivers-with-efi-on-mac-to-prevent-overheating/613573#613573

install is straighforward without any hick-ups
system works, wifi has reasonable speed
startup time 26 seconds to login, without time to type password 59 seconds to desktop
quick startup of Chrome browser
download and upload speed were 98 Mbps and 93 Mbps respectively
watching youtube videos is possible
apps work 




system sometimes is unresponsive for longer time (10-20 seconds). After showing a black or completely distorted screen for roughly 1-3 seconds, the display is refreshed and the system is responsive again. There seems to be a relation with loading new web pages in Chrome. Loading a sharepoint page seems to completely drown the device, bringing it to 100% CPU load and creating a relatively loud fan noise. Just scrolling a complex sharepoint page (for example the home page of my work account) brings the CPU load to 100% directly. 

when system runs out of power, the behaviour is unpredictable. At first the system does not seem to react to inputs. After some attempts the system will start, but the system will also report that the shutdown was unexpected. 


